### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by DomAmato** [FRedEnergy/rabbit-gui#12]
This isn't exactly an issue but do you have any examples of how to use this for building a gui and an image of the resulting tutorial

**Comment by abvadabra** [comment]
I promise I will provide some examples within a week, but if you need it right now you can take a look at my [QReport](https://github.com/FRedEnergy/q-report/tree/master/src/main/kotlin/ru/redenergy/report/client/ui) mod in which I used rabbit gui for user interfaces, it is written in Kotlin but I hope syntax will be clear for Java developer

**Comment by DomAmato** [comment]
Thanks that looks like a good place to start

**Comment by abvadabra** [comment]
Just pushed first example show with basic button usage, you can find it in `example/` folder. More examples will be published soon. I also must say that I am not a native english speaker and you might notice some problems with grammar, so feel free to correct me

**Comment by DomAmato** [comment]
Its no problem your English is quite good but if I notice something I will let ya know. I also played around a bit and made a quick and messy tutorial for my team to follow using the Kotlin example you mentioned.

https://github.com/Digital-Youth-Network/Gui-Tutorial

**Comment by DomAmato** [comment]
I am going to close this issue thanks for your help and quick responses to everything!
