### ISSUE TITLE
ScrollableDisplayList doesn't scroll to bottom with long lists

### ISSUE THREAD

**Issue by DomAmato** [FRedEnergy/rabbit-gui#17]
The problem is with these two lines of code
https://github.com/FRedEnergy/rabbit-gui/blob/master/src/main/java/com/rabbit/gui/component/list/ScrollableDisplayList.java#L51

and

https://github.com/FRedEnergy/rabbit-gui/blob/master/src/main/java/com/rabbit/gui/component/list/ScrollableDisplayList.java#L71

When a list gets over 300 scolling no longer takes you to the bottom of the list

I changed those lines to this since scrolling to the bottom tended to show a lot of blank space as well

```
int slotPosY = ((getY() + i * slotHeight) - (int) ((this.slotHeight * scrollBar.getProgress() * this.content.size()) - ((this.height - this.slotHeight) * (scrollBar.getProgress())/ 1)));
```

**Comment by abvadabra** [comment]
That's the problems with which i've been struggling a lot! Your solution (even if it's leaves blank space) looks very nice, I will merge it into the project.

I also want to thank you for all your contribution to the project, it's great that someone is interested in this as well

**Comment by abvadabra** [comment]
I am going to close this issue, thanks you
